AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    deals-app

    Sample SAM Template for deals-app

Resources:
    Functions:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/functions/template.yaml
    API:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/api/template.yaml
    DB:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/db/template.yaml
