AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    deals-app

    Sample SAM Template for deals-app

Parameters:
    UserPoolArn:
        Type: String
        Description: Cognito Identity Pool Id

Resources:
    Functions:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/functions/template.yaml
            Parameters:
                UserPoolArn: !Ref UserPoolArn
    DB:
        Type: AWS::Serverless::Application
        Properties:
            Location: src/db/template.yaml
