AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    lambda resources

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10
        MemorySize: 1024
        Runtime: nodejs16.x
        Handler: index.handler
        Architectures:
            - x86_64
        Environment:
            Variables:
                NODE_ENV: !FindInMap [EnvironmentVariableMap, NodeEnv, !Ref DeploymentAccount]

Parameters:
    CreateOrUpdateContactsQueueArn:
        Type: String
    ChangeContactEmailQueueArn:
        Type: String
    AlarmBreachQueueArn:
        Type: String
    CreateOrUpdateContactsLayerRef:
        Type: String
    DeploymentAccount:
        Type: String

Mappings:
    EnvironmentVariableMap:
        NodeEnv:
            sandbox: development
            staging: staging
            production: production

Resources:
    CreateOrUpdateContacts:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: create-or-update-contacts/
            Events:
                CreateOrUpdateContactsQueue:
                    Type: SQS
                    Properties:
                        Queue: !Ref CreateOrUpdateContactsQueueArn
            Layers:
                - !Ref CreateOrUpdateContactsLayerRef
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
                EntryPoints:
                    - index.ts
                External:
                    - "/opt/nodejs"
    ChangeContactEmail:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: change-contact-email/
            Events:
                ChangeContactEmailQueue:
                    Type: SQS
                    Properties:
                        Queue: !Ref ChangeContactEmailQueueArn
            Layers:
                - !Ref CreateOrUpdateContactsLayerRef
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
                EntryPoints:
                    - index.ts
                External:
                    - "/opt/nodejs"

    AlarmBreach:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: alarm-breach/
            Events:
                AlarmBreachQueue:
                    Type: SQS
                    Properties:
                        Queue: !Ref AlarmBreachQueueArn
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - index.ts
